# Generated by Django 6.0.6 on 2026-06-05 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0002_otprequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otprequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otp_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
