# Generated by Django 6.0.6 on 2026-06-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0003_alter_otprequest_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
