# Generated by Django 6.0.6 on 2026-06-05 21:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0009_foodtale"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodTalePhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "food_tale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="atlas.foodtale",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attached_food_tale_photos",
                        to="atlas.attachment",
                    ),
                ),
            ],
            options={
                "db_table": "food_tale_photos",
            },
        ),
    ]
