# Generated by Django 6.0.6 on 2026-06-05 22:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0010_foodtalephoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodtale",
            name="liked_food_tales_count",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="FoodTaleLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "food_tale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="atlas.foodtale",
                    ),
                ),
                (
                    "liked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_food_tales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "food_tale_likes",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("food_tale", "liked_by"),
                        name="uniq_food_tale_like_per_user",
                    )
                ],
            },
        ),
    ]
