# Generated by Django 6.0.6 on 2026-06-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0011_foodtale_liked_food_tales_count_foodtalelike"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodtale",
            name="is_public",
        ),
        migrations.AddField(
            model_name="foodtale",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("friends", "Friends"),
                    ("private", "Private"),
                ],
                default="friends",
                max_length=32,
            ),
        ),
    ]
