# Generated by Django 6.0.6 on 2026-06-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0013_user_followers_count_user_following_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodtale",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("followers", "Followers"),
                    ("private", "Private"),
                ],
                default="followers",
                max_length=32,
            ),
        ),
    ]
