# Generated by Django 6.0.6 on 2026-06-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0014_alter_foodtale_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
