# Generated by Django 6.0.6 on 2026-06-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0015_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
