# Generated by Django 6.0.6 on 2026-06-06 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0016_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodtale",
            name="dish",
        ),
        migrations.RemoveField(
            model_name="foodtale",
            name="outlet",
        ),
        migrations.RemoveField(
            model_name="foodtale",
            name="user",
        ),
        migrations.RemoveField(
            model_name="foodtalephoto",
            name="food_tale",
        ),
        migrations.RemoveConstraint(
            model_name="foodtalelike",
            name="uniq_food_tale_like_per_user",
        ),
        migrations.RemoveField(
            model_name="foodtalelike",
            name="food_tale",
        ),
        migrations.RemoveField(
            model_name="foodtalelike",
            name="liked_by",
        ),
        migrations.DeleteModel(
            name="FoodTalePhoto",
        ),
        migrations.DeleteModel(
            name="FoodTale",
        ),
        migrations.DeleteModel(
            name="FoodTaleLike",
        ),
    ]
