# Generated by Django 6.0.6 on 2026-06-06 19:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0017_remove_foodtale_dish_remove_foodtale_outlet_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("would_order_again", models.BooleanField(default=True)),
                ("story", models.TextField(blank=True, null=True)),
                ("liked_tales_count", models.IntegerField(default=0)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("followers", "Followers"),
                            ("private", "Private"),
                        ],
                        default="followers",
                        max_length=32,
                    ),
                ),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tales",
                        to="atlas.dish",
                    ),
                ),
                (
                    "outlet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tales",
                        to="atlas.outlet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tales",
            },
        ),
        migrations.CreateModel(
            name="TalePhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attached_tale_photos",
                        to="atlas.attachment",
                    ),
                ),
                (
                    "tale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="atlas.tale",
                    ),
                ),
            ],
            options={
                "db_table": "tale_photos",
            },
        ),
        migrations.CreateModel(
            name="TaleLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "liked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_tales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="atlas.tale",
                    ),
                ),
            ],
            options={
                "db_table": "tale_likes",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tale", "liked_by"), name="uniq_tale_like_per_user"
                    )
                ],
            },
        ),
    ]
