# Generated by Django 6.0.6 on 2026-06-11 16:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0018_tale_talephoto_talelike"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=255, unique=True)),
                ("value", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, null=True)),
                ("is_depreciated", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "configs",
            },
        ),
    ]
