# Generated by Django 6.0.6 on 2026-06-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0019_config"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dish",
            old_name="public_foodtales_count",
            new_name="public_tales_count",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="public_food_tales_count",
            new_name="public_tales_count",
        ),
    ]
