# Generated by Django 6.0.6 on 2026-06-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0020_rename_tales_count_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="food_tales_count",
            new_name="tales_count",
        ),
    ]
