# Generated by Django 6.0.6 on 2026-06-13 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0021_rename_food_tales_count_user_tales_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="tale",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attached_tale_photos",
                to="atlas.attachment",
            ),
        ),
        migrations.DeleteModel(
            name="TalePhoto",
        ),
    ]
