# Generated by Django 6.0.6 on 2026-06-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0022_tale_photo_delete_talephoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="tale",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
