# Generated by Django 6.0.6 on 2026-06-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0023_tale_published_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tale",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("followers", "Followers"),
                    ("private", "Private"),
                ],
                default="public",
                max_length=32,
            ),
        ),
    ]
