# Generated by Django 6.0.6 on 2026-06-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0024_alter_tale_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tale",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="public",
                max_length=32,
            ),
        ),
    ]
