# Generated by Django 6.0.6 on 2026-06-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0025_alter_tale_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
