# Generated by Django 6.0.6 on 2026-06-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0026_user_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="feed_type",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
